// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HivCare.Repository.PhatNH.Models;

public partial class DoctorAvailabilityPhatNh
{
    public int DoctorAvailabilityPhatNhiD { get; set; }

    public int DoctorPhatNhiD { get; set; }

    public string DayOfWeek { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public DateTime? SpecificDate { get; set; }

    public int? MaxAppointments { get; set; }

    public DateTime? BreakStartTime { get; set; }

    public DateTime? BreakEndTime { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public bool IsEmergencyAvailable { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual DoctorPhatNh DoctorPhatNh { get; set; }
}