// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace HivCare.GraphQLClients.BlazorWAS.PhatNH.Models;


public partial class DoctorAvailabilityPhatNh
{
    [Required]
    public int DoctorAvailabilityPhatNhiD { get; set; }
    [Required]
    public int DoctorPhatNhiD { get; set; }
    [Required]
    public string DayOfWeek { get; set; }
    [Required]
    public DateTime? StartTime { get; set; }
    [Required]
    public DateTime? EndTime { get; set; }
    [Required]
    public DateTime? SpecificDate { get; set; }
    [Required]
    public int? MaxAppointments { get; set; }
    [Required]
    public DateTime? BreakStartTime { get; set; }
    [Required]
    public DateTime? BreakEndTime { get; set; }
    [Required]
    public string Status { get; set; }
    public string Notes { get; set; }
    [Required]
    public bool IsEmergencyAvailable { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual DoctorPhatNh DoctorPhatNh { get; set; }
}
public partial class DoctorAvailabilityPhatNhsResponse
{
    public List<DoctorAvailabilityPhatNh> doctorAvailabilityPhatNhs { get; set; }
}
public partial class DoctorAvailabilityPhatNhsWithPaginationResponse
{
    public PaginationResult searchWithPaging { get; set; }
}
public class PaginationResult
{
    public int totalPages { get; set; }
    public int currentPage { get; set; }
    public int pageSize { get; set; }
    public int totalItems { get; set; }
    public List<DoctorAvailabilityPhatNh> items { get; set; }
}

public class ClassSearchDoctorRequestInput
{
    public int? CurrentPage { get; set; } = 1;
    public int? PageSize { get; set; } = 1;
    public string? DayOfWeek { get; set; }
    public string? Notes { get; set; }
    public string? Status { get; set; }
}


public partial class DoctorAvailabilityPhatNhdResponse
{
    public DoctorAvailabilityPhatNh doctorAvailabilityPhatNhById { get; set; }
}
public partial class UpdateDoctorAvailabilityPhatNhdResponse
{
    public int updateDoctorAvailabilityPhatNh { get; set; }
}
public partial class CreateDoctorAvailabilityPhatNhdResponse
{
    public int createDoctorAvailabilityPhatNh { get; set; }
}
public partial class DeleteDoctorAvailabilityPhatNhdResponse
{
    public bool deleteDoctorAvailabilityPhatNh { get; set; }
}
