// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HivCare.GraphQLClients.BlazorWAS.PhatNH.Models;


public partial class DoctorPhatNh
{
    public int DoctorPhatNhiD { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string LicenseNumber { get; set; }

    public string Specialization { get; set; }

    public int? ExperienceYears { get; set; }

    public decimal? ConsultationFee { get; set; }

    public string Department { get; set; }

    public string Bio { get; set; }

    public decimal? Rating { get; set; }

    public DateTime? PracticingSince { get; set; }

    public string CertificationDetails { get; set; }

    public bool IsAvailableAfterHours { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<DoctorAvailabilityPhatNh> DoctorAvailabilityPhatNhs { get; set; } = new List<DoctorAvailabilityPhatNh>();
}

public partial class DoctorPhatNhsResponse
{
    public List<DoctorPhatNh> doctorPhatNhs { get; set; }
}